name: "Build & Deploy"

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run
        run: |
          echo "Hello, World"
          echo "This is a sample workflow"